
"""
Advanced Password Strength Checker
Features:
- Checks length, uppercase, lowercase, digits, special characters
- Checks for common passwords / blocklist
- Detects dictionary words (basic) and repeated characters/sequences
- Estimates entropy and provides actionable suggestions
- CLI interactive and can be used as a module

Author: Generated by ChatGPT
"""
import re
import math

# Small common passwords blocklist (extendable)
COMMON_PASSWORDS = {
    "123456","password","123456789","12345678","12345","qwerty","abc123","football",
    "letmein","monkey","iloveyou","admin","welcome","login","passw0rd"
}

# Small dictionary words set for basic dictionary-word detection
DICTIONARY_SAMPLE = {
    "password", "admin", "user", "login", "welcome", "qwerty", "hello", "letmein",
    "secret", "football", "monkey", "home", "love", "iloveyou"
}

def estimate_entropy(password: str) -> float:
    """Estimate Shannon-like entropy based on character sets used and length."""
    pool = 0
    if re.search(r"[a-z]", password): pool += 26
    if re.search(r"[A-Z]", password): pool += 26
    if re.search(r"[0-9]", password): pool += 10
    if re.search(r"[!@#\\$%\\^&\\*\\(\\)_\\+\\-=\[\]{};':\"\\|,.<>\\/?`~\\\\]", password): pool += 32
    # If none matched, minimal pool of 1 to avoid log2(0)
    pool = max(pool, 1)
    entropy = len(password) * math.log2(pool)
    return entropy

def has_sequence(password: str, seq_len: int = 3) -> bool:
    """Detect simple increasing/decreasing sequences like 'abc', '123', '987'."""
    pw = password.lower()
    for i in range(len(pw) - seq_len + 1):
        segment = pw[i:i+seq_len]
        # check alphabetic sequence
        if all(ord(segment[j+1]) - ord(segment[j]) == 1 for j in range(len(segment)-1)):
            return True
        if all(ord(segment[j]) - ord(segment[j+1]) == 1 for j in range(len(segment)-1)):
            return True
    return False

def has_repeated_chars(password: str, repeat_threshold: int = 3) -> bool:
    """Detect repeated character sequences like 'aaa' or '1111'."""
    return bool(re.search(r"(.)\1{" + str(repeat_threshold-1) + r",}", password))

def contains_dictionary_word(password: str) -> bool:
    """Basic check if any dictionary sample word is present in password (case-insensitive)."""
    pw = password.lower()
    for word in DICTIONARY_SAMPLE:
        if word in pw:
            return True
    return False

def evaluate_password(password: str) -> dict:
    """Return a detailed evaluation and suggestions."""
    result = {}
    length = len(password)
    result['length'] = length
    result['has_lower'] = bool(re.search(r"[a-z]", password))
    result['has_upper'] = bool(re.search(r"[A-Z]", password))
    result['has_digit'] = bool(re.search(r"[0-9]", password))
    result['has_special'] = bool(re.search(r"[!@#\\$%\\^&\\*\\(\\)_\\+\\-=\[\]{};':\"\\|,.<>\\/?`~\\\\]", password))
    result['common_password'] = password.lower() in COMMON_PASSWORDS
    result['contains_dictionary_word'] = contains_dictionary_word(password)
    result['has_sequence'] = has_sequence(password)
    result['has_repeated_chars'] = has_repeated_chars(password)
    result['entropy'] = round(estimate_entropy(password), 2)

    # Score calculation (0-100)
    score = 0
    # length contribution
    if length >= 12:
        score += 30
    elif length >= 8:
        score += 15
    else:
        score += 5

    # character variety
    score += 15 if result['has_lower'] and result['has_upper'] else (7 if result['has_lower'] or result['has_upper'] else 0)
    score += 20 if result['has_digit'] else 5
    score += 20 if result['has_special'] else 5

    # penalties
    if result['common_password']:
        score -= 40
    if result['contains_dictionary_word']:
        score -= 15
    if result['has_sequence']:
        score -= 10
    if result['has_repeated_chars']:
        score -= 10

    # entropy bonus (small)
    if result['entropy'] >= 60:
        score += 10
    elif result['entropy'] >= 40:
        score += 5

    # clamp
    score = max(0, min(100, score))
    result['score'] = score

    # qualitative rating
    if score >= 80:
        rating = "Very Strong"
    elif score >= 60:
        rating = "Strong"
    elif score >= 40:
        rating = "Medium"
    elif score >= 20:
        rating = "Weak"
    else:
        rating = "Very Weak"
    result['rating'] = rating

    # suggestions
    suggestions = []
    if length < 12:
        suggestions.append("Increase length to at least 12 characters (longer is better).")
    if not result['has_upper']:
        suggestions.append("Add uppercase letters (A-Z).")
    if not result['has_lower']:
        suggestions.append("Add lowercase letters (a-z).")
    if not result['has_digit']:
        suggestions.append("Include digits (0-9).")
    if not result['has_special']:
        suggestions.append("Include special characters (e.g., !@#$%).")
    if result['common_password']:
        suggestions.append("Avoid common passwords (e.g., '123456', 'password').")
    if result['contains_dictionary_word']:
        suggestions.append("Avoid using dictionary words; combine unrelated words or use passphrases.")
    if result['has_sequence']:
        suggestions.append("Avoid sequences like 'abcd' or '1234'.")
    if result['has_repeated_chars']:
        suggestions.append("Avoid repeated characters like 'aaaa' or '1111'.")
    if result['entropy'] < 40:
        suggestions.append("Increase character variety to raise entropy.")
    if not suggestions:
        suggestions.append("Good job — password looks strong. Consider using a password manager.")

    result['suggestions'] = suggestions
    return result

def print_evaluation(result: dict):
    print("Password Strength Evaluation")
    print("-----------------------------")
    print(f"Length: {result['length']}")
    print(f"Entropy (bits): {result['entropy']}")
    print(f"Score (0-100): {result['score']} -> {result['rating']}")
    print("Flags:")
    for k in ['has_lower','has_upper','has_digit','has_special','common_password','contains_dictionary_word','has_sequence','has_repeated_chars']:
        print(f" - {k}: {result[k]}")
    print("\nSuggestions:")
    for s in result['suggestions']:
        print(" * " + s)

def main():
    print("Advanced Password Strength Checker")
    pw = input("Enter password to evaluate: ").strip()
    res = evaluate_password(pw)
    print_evaluation(res)

if __name__ == "__main__":
    main()
